# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80cc32cd333af28a1990288e241424cb1cfbdf76a546fbd679ac58447129f820f6e2b92f9b3ac52039892475053ece554d1c015e5f056827d6b8ae52878efe58

test:
  secret_key_base: 3200681d8b953a2ef3728a39198a593d84b1130f079e48491dfb944ea4e37cf50029e3ce761a3cf65e783d3b3bf953b04f87e6e295c4d771498b8743b32f2bd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
